### ISSUE TITLE
Release trained weights

### ISSUE THREAD

**Issue by nhafez** [liyi14/mx-DeepIM#8]
Since the paper claims the network works on unseen objects as well, would it be possible to share the trained checkpoint files for all three datasets (the data processing scripts are not yet available for Occlsion and T-LESS datasets).

**Comment by liyi14** [comment]
Currently we haven't done so since the scale of object, focal length and other type of things are different. It is a interesting topic and I think it is possible to use one network for different datasets.
But for the LINEMOD dataset and OCCLUSION dataset, they are difficult to share the checkpoint since these two datasets are highly correlated.

**Comment by liyi14** [comment]
We will release the trained model soon.

**Comment by saadhana** [comment]
It would also be useful to release the model trained on many ModelNet objects that work on unseen categories. How well can we expect the currently released model to work on unseen objects?
